### ISSUE TITLE
Help us test IPFS Desktop v0.15.0-rc1 :-)

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-desktop#1812]
In the past Electron shipped breaking changes on various platforms, and we had to update it recently, so let's do additonal smoke-tests to ensure there is no blocker on any platform.

## How to help?

RC1 package for your platform can be fetched from:
https://bafybeic36zxgauv6xviy2tc7gumejdixvs7bt4gpskk2phkkjozo55qhey.ipfs.dweb.link/ipfs-desktop-v0.15.0-rc1

Manual test steps are at: https://github.com/ipfs/ipfs-desktop/blob/main/DEVELOPER-NOTES.md#manual-testing

Comment with the version you used and if it worked OK, or were there any issues.
We will apply feedback to the matrix below and make a decision if RC1 is good enough, or needs more work.

(@lidel will be back on Tuesday)

## TODO: results / issues

Windows:
  - [x] IPFS-Desktop-Setup-0.15.0.exe

macOS:
- [x] IPFS-Desktop-0.15.0.dmg

Linux:
- [ ] ipfs-desktop-0.15.0-linux-amd64.deb
- [ ] ipfs-desktop-0.15.0-linux-amd64.snap
- [x] ipfs-desktop-0.15.0-linux-x64.tar.xz
- [x] ipfs-desktop-0.15.0-linux-x86_64.AppImage
- [ ] ipfs-desktop-0.15.0-linux-x86_64.rpm

**Comment by TheDiscordian** [comment]
Linux:

```
[user@TheDesktop ~]$ lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        21.0.3
Codename:       Ornara
```

Tested both the AppImage and tgz package, works great :tada: . No issues of note that I uncovered.

**Comment by fusetim** [comment]
Linux: 
```
$ inxi -S
System:    
    Host: nemesis 
    Kernel: 5.10.23-1-MANJARO x86_64 
    bits: 64 
    Desktop: KDE Plasma 5.21.3 
    Distro: Manjaro Linux 
```
The AppImage version seems to work perfectly. Tray on Linux works. Did not test other packages.

**Comment by ravenclaw900** [comment]
macOS:
```
$ sw_vers                       
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G8022
```
Seems to be working fine, tray and interface are good.

**Comment by jadbox** [comment]
A quick test on Windows 10 seems to be working fine for reading IPFS content.

**Comment by lidel** [comment]
Thank you all! 
Looks good enough, shipping: https://github.com/ipfs/ipfs-desktop/releases/tag/v0.15.0
If you find any issues, feel free to fill a bug :pray:
