### ISSUE TITLE
Better Error Handling Around ipfsd-ctl

### ISSUE THREAD

**Issue by whizzzkid** [ipfs/ipfs-desktop#2546]
[`ipfsd-ctl`](https://www.npmjs.com/package/ipfsd-ctl) is used to control the kubo node shipped with ipfs-desktop, however we're not catching all of those errors effectively. These do not make it to `errors.log` or reported in `countly` metrics.

For example these [Config Missing](https://github.com/ipfs/ipfs-desktop/issues?q=is%3Aissue+%22Unexpected+end+of+JSON+input%22+) errors can be handled and an alternative can be provided instead of asking users to create a bug report.

```[tasklist]
### Tasks
- [ ] Instrument Error and Catch those. Report those errors in `errors.log`
- [ ] Provide an alternative to users in case this happens.
- [ ] Report this on countly
```
