### ISSUE TITLE
[Epic][Tray] Fix Tray Issues

### ISSUE THREAD

**Issue by whizzzkid** [ipfs/ipfs-desktop#2600]
Recently the tray has been finicky, causing different issues.

```[tasklist]
### Tasks
- [x] https://github.com/ipfs/ipfs-desktop/issues/2577
- [x] https://github.com/ipfs/ipfs-desktop/issues/2591
- [ ] https://github.com/ipfs/ipfs-desktop/issues/2595
- [ ] https://github.com/ipfs/ipfs-desktop/issues/2599
- [ ] Multi-Env tests for making sure tray is working.
```

**Comment by SgtPooki** [comment]
idk if we can test the tray. there are numerous issues around this with electron, and I think we would need some sort of os-level testing framework to run system tray e2e tests. Closing this as resolved for now
